In [37]:
import tensorflow as tf

import keras
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import adam_v2

import numpy as np
import matplotlib.pyplot as plt

### Read data

In [60]:
batch_size = 64
num_classes = 10
epochs = 120

In [80]:
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

x_train = x_train.reshape(60000, 784).astype('float32')
x_test = x_test.reshape(10000, 784).astype('float32')

x_train /= 255
x_test /= 255

y_train = y_train.astype('float32')
y_test = y_test.astype('float32')

y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

In [94]:
print(y_test[0])
print(y_test[1])
print(y_test[2])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


### Create model

In [97]:
model = Sequential()

model.add(Dense(50, activation='relu', input_shape=(784,)))
model.add(Dropout(0.2))

model.add(Dense(50, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(num_classes, activation='softmax'))

model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_30 (Dense)            (None, 50)                39250     
                                                                 
 dropout_20 (Dropout)        (None, 50)                0         
                                                                 
 dense_31 (Dense)            (None, 50)                2550      
                                                                 
 dropout_21 (Dropout)        (None, 50)                0         
                                                                 
 dense_32 (Dense)            (None, 10)                510       
                                                                 
Total params: 42,310
Trainable params: 42,310
Non-trainable params: 0
_________________________________________________________________


In [101]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',#tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.5),
    metrics=['accuracy']
)

In [102]:
%%time
history = model.fit(
    x_train, y_train,
    batch_size=batch_size,
    epochs=epochs,
    verbose=1,
    validation_data=(x_test, y_test)
)

Epoch 1/120
938/938 [==============================] - 2s 2ms/step - loss: 0.3228 - accuracy: 0.8816 - val_loss: 0.3740 - val_accuracy: 0.8736
Epoch 2/120
938/938 [==============================] - 1s 2ms/step - loss: 0.3272 - accuracy: 0.8800 - val_loss: 0.3618 - val_accuracy: 0.8717
Epoch 3/120
938/938 [==============================] - 1s 2ms/step - loss: 0.3191 - accuracy: 0.8827 - val_loss: 0.3682 - val_accuracy: 0.8702
Epoch 4/120
938/938 [==============================] - 1s 1ms/step - loss: 0.3156 - accuracy: 0.8834 - val_loss: 0.3567 - val_accuracy: 0.8734
Epoch 5/120
938/938 [==============================] - 1s 2ms/step - loss: 0.3114 - accuracy: 0.8855 - val_loss: 0.3495 - val_accuracy: 0.8772
Epoch 6/120
938/938 [==============================] - 1s 2ms/step - loss: 0.3117 - accuracy: 0.8858 - val_loss: 0.3525 - val_accuracy: 0.8755
Epoch 7/120
938/938 [==============================] - 1s 2ms/step - loss: 0.3051 - accuracy: 0.8881 - val_loss: 0.3765 - val_accuracy: 0.8673

Epoch 58/120
938/938 [==============================] - 1s 2ms/step - loss: 0.2470 - accuracy: 0.9081 - val_loss: 0.3465 - val_accuracy: 0.8818
Epoch 59/120
938/938 [==============================] - 1s 1ms/step - loss: 0.2462 - accuracy: 0.9082 - val_loss: 0.3519 - val_accuracy: 0.8828
Epoch 60/120
938/938 [==============================] - 1s 2ms/step - loss: 0.2471 - accuracy: 0.9075 - val_loss: 0.3649 - val_accuracy: 0.8804
Epoch 61/120
938/938 [==============================] - 2s 2ms/step - loss: 0.2455 - accuracy: 0.9082 - val_loss: 0.3485 - val_accuracy: 0.8783
Epoch 62/120
938/938 [==============================] - 1s 2ms/step - loss: 0.2420 - accuracy: 0.9106 - val_loss: 0.3608 - val_accuracy: 0.8807
Epoch 63/120
938/938 [==============================] - 1s 2ms/step - loss: 0.2431 - accuracy: 0.9089 - val_loss: 0.3636 - val_accuracy: 0.8809
Epoch 64/120
938/938 [==============================] - 1s 2ms/step - loss: 0.2405 - accuracy: 0.9107 - val_loss: 0.3559 - val_accuracy:

Epoch 115/120
938/938 [==============================] - 1s 2ms/step - loss: 0.2178 - accuracy: 0.9181 - val_loss: 0.4009 - val_accuracy: 0.8787
Epoch 116/120
938/938 [==============================] - 1s 2ms/step - loss: 0.2226 - accuracy: 0.9180 - val_loss: 0.3815 - val_accuracy: 0.8752
Epoch 117/120
938/938 [==============================] - 1s 2ms/step - loss: 0.2199 - accuracy: 0.9167 - val_loss: 0.3769 - val_accuracy: 0.8778
Epoch 118/120
938/938 [==============================] - 1s 2ms/step - loss: 0.2213 - accuracy: 0.9183 - val_loss: 0.3875 - val_accuracy: 0.8816
Epoch 119/120
938/938 [==============================] - 1s 2ms/step - loss: 0.2174 - accuracy: 0.9188 - val_loss: 0.4170 - val_accuracy: 0.8785
Epoch 120/120
938/938 [==============================] - 1s 2ms/step - loss: 0.2201 - accuracy: 0.9183 - val_loss: 0.3778 - val_accuracy: 0.8805
CPU times: user 5min 58s, sys: 1min 5s, total: 7min 4s
Wall time: 3min 4s


In [100]:
score = model.evaluate(x_test, y_test, verbose=0)
print(f'test loss {score[0]:.3f}')
print(f'test accuracy {score[1]:.3f}')

test loss 0.340
test accuracy 0.882
