In [2]:
import tensorflow as tf

import keras
from keras.datasets import fashion_mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, BatchNormalization
from keras.optimizers import adam_v2

import numpy as np
import matplotlib.pyplot as plt

### Read data

In [3]:
batch_size = 64
num_classes = 10
epochs = 120

In [4]:
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

x_train = x_train.reshape(60000, 784).astype('float32')
x_test = x_test.reshape(10000, 784).astype('float32')

x_train /= 255
x_test /= 255

y_train = y_train.astype('float32')
y_test = y_test.astype('float32')

y_train = tf.keras.utils.to_categorical(y_train)
y_test = tf.keras.utils.to_categorical(y_test)

In [5]:
print(y_test[0])
print(y_test[1])
print(y_test[2])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]


### Create model

In [7]:
model = Sequential()

model.add(Dense(50, activation='relu', input_shape=(784,)))
# model.add(Dropout(0.2))
model.add(BatchNormalization(momentum=0.8))

model.add(Dense(50, activation='relu'))
# model.add(Dropout(0.2))
model.add(BatchNormalization(momentum=0.8))

model.add(Dense(num_classes, activation='softmax'))

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 50)                39250     
                                                                 
 batch_normalization (BatchN  (None, 50)               200       
 ormalization)                                                   
                                                                 
 dense_1 (Dense)             (None, 50)                2550      
                                                                 
 batch_normalization_1 (Batc  (None, 50)               200       
 hNormalization)                                                 
                                                                 
 dense_2 (Dense)             (None, 10)                510       
                                                                 
Total params: 42,710
Trainable params: 42,510
Non-traina

In [6]:
?BatchNormalization

In [8]:
model.compile(
    loss='categorical_crossentropy',
    optimizer='adam',#tf.keras.optimizers.SGD(learning_rate=0.01, momentum=0.5),
    metrics=['accuracy']
)

In [9]:
%%time
history = model.fit(
    x_train, y_train,
    batch_size=batch_size,
    epochs=epochs,
    verbose=1,
    validation_data=(x_test, y_test)
)

Epoch 1/120
938/938 [==============================] - 3s 2ms/step - loss: 0.5048 - accuracy: 0.8239 - val_loss: 0.4431 - val_accuracy: 0.8443
Epoch 2/120
938/938 [==============================] - 2s 2ms/step - loss: 0.3779 - accuracy: 0.8629 - val_loss: 0.3770 - val_accuracy: 0.8653
Epoch 3/120
938/938 [==============================] - 2s 2ms/step - loss: 0.3462 - accuracy: 0.8738 - val_loss: 0.3673 - val_accuracy: 0.8639
Epoch 4/120
938/938 [==============================] - 2s 2ms/step - loss: 0.3286 - accuracy: 0.8801 - val_loss: 0.3624 - val_accuracy: 0.8716
Epoch 5/120
938/938 [==============================] - 2s 2ms/step - loss: 0.3113 - accuracy: 0.8866 - val_loss: 0.3601 - val_accuracy: 0.8700
Epoch 6/120
938/938 [==============================] - 2s 2ms/step - loss: 0.3014 - accuracy: 0.8902 - val_loss: 0.3546 - val_accuracy: 0.8690
Epoch 7/120
938/938 [==============================] - 2s 2ms/step - loss: 0.2893 - accuracy: 0.8939 - val_loss: 0.3439 - val_accuracy: 0.8762

Epoch 58/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1523 - accuracy: 0.9423 - val_loss: 0.4206 - val_accuracy: 0.8724
Epoch 59/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1517 - accuracy: 0.9425 - val_loss: 0.4131 - val_accuracy: 0.8787
Epoch 60/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1490 - accuracy: 0.9436 - val_loss: 0.4074 - val_accuracy: 0.8817
Epoch 61/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1507 - accuracy: 0.9438 - val_loss: 0.4257 - val_accuracy: 0.8760
Epoch 62/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1480 - accuracy: 0.9443 - val_loss: 0.4371 - val_accuracy: 0.8773
Epoch 63/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1485 - accuracy: 0.9453 - val_loss: 0.4278 - val_accuracy: 0.8780
Epoch 64/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1487 - accuracy: 0.9444 - val_loss: 0.4043 - val_accuracy:

Epoch 115/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1121 - accuracy: 0.9585 - val_loss: 0.5186 - val_accuracy: 0.8747
Epoch 116/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1160 - accuracy: 0.9564 - val_loss: 0.5182 - val_accuracy: 0.8751
Epoch 117/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1136 - accuracy: 0.9568 - val_loss: 0.5115 - val_accuracy: 0.8743
Epoch 118/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1104 - accuracy: 0.9583 - val_loss: 0.5050 - val_accuracy: 0.8742
Epoch 119/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1101 - accuracy: 0.9584 - val_loss: 0.5337 - val_accuracy: 0.8674
Epoch 120/120
938/938 [==============================] - 2s 2ms/step - loss: 0.1116 - accuracy: 0.9578 - val_loss: 0.5063 - val_accuracy: 0.8720
CPU times: user 7min 41s, sys: 1min 32s, total: 9min 14s
Wall time: 3min 36s


In [100]:
score = model.evaluate(x_test, y_test, verbose=0)
print(f'test loss {score[0]:.3f}')
print(f'test accuracy {score[1]:.3f}')

test loss 0.340
test accuracy 0.882
